// client/src/components/DashboardPage.vue
<template>
    <nav>
        <li><router-link class="m-3" to="/dashboard/products">PRODUCTS</router-link></li>
        <li><router-link class="m-3" to="/dashboard/orders">ORDERS</router-link></li>
        <li><router-link class="m-3" to="/dashboard/settings">SETTINGS</router-link></li>
    </nav>
</template>

<script>
export default {
    name: "DashboardPage"
}
</script>

<style scoped>
nav {
    text-align: center;
    list-style-type: none;
}
</style>

// src/components/dashboardpage.jsx
import React from "react";

class DashboardPage extends React.Component {
    render() {
        return (
            <div className="container-fluid text-center">
                <h1 class="m-5">Dashboard</h1>
                <ul className="list-unstyled mt-5"> 
                    <li className="py-1"><a className="h5" href="/dashboard/products">PRODUCTS</a></li>
                    <li className="py-1"><a className="h5" href="/dashboard/orders">ORDERS</a></li>
                    <li className="py-1"><a className="h5" href="/dashboard/settings">SETTINGS</a></li>
                </ul>
            </div>
        );
    }
}

export default DashboardPage;
